version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: './docker/Dockerfile.dev'
    container_name: search-my-dish-backend
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/backend
    tty: true
    environment:
      - DATABASE_URL=postgres://app:password@db:5432/searchmydish
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "diesel migration run && cargo watch -x run"
  
  db:
    image: postgres:14-alpine 
    ports: 
      - '5432:5432'
    container_name: search-my-dish-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: searchmydish
    # volumes:
    #   - ./docker/db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
