version: "3"

services:
  serve:
    build:
      context: .
      dockerfile: './Dockerfile'
    container_name: search-my-dish-backend
    ports:
      - '8088:8088'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://admin:password@db:5432/postgres
    command: /bin/sh -c "diesel setup && cargo watch -x run "
    tty: true

  db:
    image: postgres:14-alpine 
    ports: 
      - '5432:5432'
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5