version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: './backend/Dockerfile'
    container_name: backend
    ports:
      - '8088:8088'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgres://root:password@db:5432/searchmydish
    command: /bin/sh -c "diesel migration run && cargo watch -x run "
    tty: true

  db:
    image: postgres:14-alpine 
    ports: 
      - '5432:5432'
    container_name: postgresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: searchmydish
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5