version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: './docker/Dockerfile.dev'
    container_name: search-my-dish-backend
    ports:
      - '8088:8080'
    volumes:
      - ./backend:/backend
    tty: true
    depends_on:
      - db

  db:
    image: postgres:14-alpine 
    ports: 
      - '5442:5432'
    container_name: search-my-dish-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: searchmydish
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data
