# 開発環境
FROM rust:1.63.0

RUN apt update -y
RUN apt upgrade -y
RUN apt install -y libpq-dev

RUN mkdir backend
WORKDIR /backend

ENV CARGO_BUILD_TARGET_DIR=/tmp/target

RUN cargo install cargo-watch diesel_cli sccache

ENV RUSTC_WRAPPER=/usr/local/cargo/bin/sccache

RUN cargo init

COPY ./backend/Cargo.toml Cargo.toml
COPY ./backend/Cargo.lock Cargo.lock

RUN cargo build

EXPOSE 8080